import Head from "next/head";

import BgScroll from "../modules/bgScroll/BgScroll";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BgScroll />
      {/* <Combiner /> */}
    </div>
  );
}
